services:
  - type: web
    name: connected-fleet-console
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm ci && npx nx build fleet-webapp --configuration=production && npx nx build fleet-backend --configuration=production
    startCommand: cd dist/apps/fleet-backend && node main.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api
